theme: jekyll-theme-minimal
title: Teleo - Jeedom plugin for Veolia Téléo
description: Jeedom plugin to retrieve water consumption from Veolia website
show_downloads: true
logo: /assets/images/logo.png
